// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "display/internal/logic/bizctx"
	_ "display/internal/logic/captcha"
	_ "display/internal/logic/category"
	_ "display/internal/logic/content"
	_ "display/internal/logic/file"
	_ "display/internal/logic/interact"
	_ "display/internal/logic/menu"
	_ "display/internal/logic/middleware"
	_ "display/internal/logic/reply"
	_ "display/internal/logic/session"
	_ "display/internal/logic/setting"
	_ "display/internal/logic/user"
	_ "display/internal/logic/view"
)
